### ISSUE TITLE
sage - indentation issue when sending line

### ISSUE THREAD

**Issue by alaindanet** [iago-lito/intim#3] opened 2018-01-26 09:29 UTC
Hi,
I have succeeded so far to use intim with [sage](http://www.sagemath.org/).
The coding syntax is the same than `python`.

When I send my lines one by one to the terminal, all is going fine.

But when I send a function definition with `<Plug>IntimSendSelection`, the indentation fails and I get an error. This problem was not occuring when using intim with `python`

Here an example:

```
# Suite
def U(a,f,n):
    if n == 0: return a
    un_1 = a
    for k in range(n):
        un = f(un_1)
        un_1 = un
    return(un)
```
I get:
![intim_bug](https://user-images.githubusercontent.com/11349327/35433461-cbbb89e8-0283-11e8-827b-aa72e4ff2cff.png)

Thank you so much for your help!

Cheers,
Alain.

**Comment by iago-lito** [comment] 2018-01-27 15:14
.. currently installing sage to reproduce, hold on ;)

**Comment by iago-lito** [comment] 2018-01-27 15:34
Yupe, confirmed.

---

-  `python` interpreter considers it's your job to indent each new line the way it has to be indented, whereas..
- `sage` interpreter automatically indents the first line of new scopes for you.

The solution may be to preprocess or not lines sent by [`<Plug>IntimSendSelection`](https://github.com/iago-lito/intim/blob/920237947821b406c8825609a962725b6ac8983b/plugin/intim.vim#L731) in a way that depends on your interpreter or your language. I'll get into this.

---

As a workaround for now, you may use [`<Plug>IntimSendChunk`](https://github.com/iago-lito/intim/blob/920237947821b406c8825609a962725b6ac8983b/doc/intim.txt#L153) instead, which should not mind about indentation, although it's a totally different way to send script lines.

Thank you for reporting :)

**Comment by iago-lito** [comment] 2018-01-27 17:42
106a9c6 should fix it. The problem actually affects every [`ipython`](https://ipython.org/install.html) interpreter, which I think `sage` interpreter is an instance.

---

Considering [deprecation](https://github.com/ipython/ipython/issues/9888) of the [old sage `%autoindent` feature](https://ask.sagemath.org/question/8117/how-to-disable-auto-indentation-on-text-mode-interface/). I have chosen to use ipython's `%cpaste` [magic command](http://ipython.readthedocs.io/en/stable/interactive/magics.html) to send selection just like we would do while pasting text to the console.

This requires the `SendSelection` function to choose now whether or not to send selection naively line-by-line or using the new [`MagicCpaste`](https://github.com/iago-lito/intim/blob/106a9c6a4e0253ece3852a2e77249dae9c664120/plugin/intim.vim#L927) procedure. So I had to introduce an new [`sendSelection`](https://github.com/iago-lito/intim/blob/106a9c6a4e0253ece3852a2e77249dae9c664120/plugin/intim.vim#L270) intim option to handle this case.

However, in order to keep basic user out of this subtle tweak. I've made this option automagically set to the right value if user's invoked interpreter is detected to be `sage` or `ipython`. This can be done with a new [hook](https://github.com/iago-lito/intim/blob/106a9c6a4e0253ece3852a2e77249dae9c664120/plugin/intim.vim#L198) triggered while user is setting an Intim option.

---

This should work transparently from now on, unless you have a very specific case to handle.

See `:help intim-autoindent` or `:help intim-sage` to keep updated :)

**Comment by alaindanet** [comment] 2018-01-27 22:09
Thank you so much! I will get a look tomorrow, it looks great =)

**Comment by alaindanet** [comment] 2018-01-29 08:08
Hi Iago,

the magical option seems not to work. I have still the indentation problem.

Moreover, The `call Intim_sendSelection('sage', 'MagicCpaste')` throws an error:
![latest-screenshot](https://user-images.githubusercontent.com/11349327/35499733-f3e17336-04d3-11e8-98c9-1ac85495f5ea.png)

Thank you so much for your help!

**Comment by iago-lito** [comment] 2018-01-29 09:59
Ay.

- For the magic to occur, `sage` must have been somehow defined as your formal invoke command by:
    ```lua
    call Intim_invokeCommand('python', 'sage')
    ```
    or
    ```lua
    call Intim_invokeCommand('sage', 'sage')
    ```
    or anything like that (see `:help intim-invoke`).. is this the case? Otherwise, could you provide the output of:
    ```lua
    :echo <SNR>29_get_invokeCommand()     
    :echo <SNR>29_get_sendSelection()
    ```
    (I wrote `29_` because it is the number that shows up in your error message. It may change if you have installed/uninstalled other plugins since then. Please use the latest one.)

- As for this `E117` error. Thanks to your report, I found out that Intim function were guaranteed to be defined *only*.. at least.. at the time of vim [`autocmd`](http://learnvimscriptthehardway.stevelosh.com/chapters/12.html) resolving (`see :help autocommand`). As a consequence, wrapping your call in something like:
    ````lua
    augroup PythonGroup
        autocmd!
        autocmd VimEnter *.py,*.sage call Intim_sendSelection('sage', 'MagicCpaste')
    augroup end
    ````

    Should fix it. I'll update the doc to warn about this.

Thanks for reporting again. Keep me updated :)

**Comment by alaindanet** [comment] 2018-01-29 10:19
Thank you for your help!

When I start Intim from my somefile.sage, I get a python session.
The output that you resquested are:
```
:echo <SNR>29_get_invokeCommand()
python
:echo <SNR>29_get_sendSelection()
LineByLine
```

I have added your wrap to my `$VIMRC`. Opening a `.sage` file results in:
![latest-screenshot](https://user-images.githubusercontent.com/11349327/35505626-f3e60a50-04e6-11e8-8fc9-419e15779420.png)

Futhermore, `call Intim_invokeCommand('python', 'sage')` throws me also an error:
![latest-screenshot](https://user-images.githubusercontent.com/11349327/35505754-64da7f16-04e7-11e8-8d5d-2c7cd32f2103.png)

**Comment by iago-lito** [comment] 2018-01-29 13:40
Thank you. So the magic is not happening because it turns out you cannot actually set your options correctly. This is another problem, if you don't mind skipping to #6 :)

**Closed as completed by iago-lito** 2018-01-29 13:40 UTC
Labels: enhancement
